import { ProviderLogos } from "@/components/project/details/assets";

export const allProvidersList = [
    // --- CORE SOCIAL ---
    {
        id: "google",
        name: "Google",
        logo: ProviderLogos.google,
        status: "available",
        type: "OAuth 2.0 / OIDC",
        flows: ["PKCE", "Implicit", "Auth Code"],
        platforms: ["Web", "iOS", "Android", "Server"],
        capabilities: ["Profile Info", "Email Verification", "Refresh Tokens"],
        limitations: "Standard Google Cloud quotas apply.",
        future: ["One-tap login integration", "People API advanced scopes", "Google Workspace Directory Sync"],
        env_vars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
        description: "The gold standard for consumer identity. Fast, reliable, and trusted by billions."
    },
    {
        id: "github",
        name: "GitHub",
        logo: ProviderLogos.github,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code", "Device Flow"],
        platforms: ["Web", "Desktop", "CLI"],
        capabilities: ["Read Org Members", "SSH Keys", "Repository Access"],
        limitations: "Email may be private depending on user settings.",
        future: ["GitHub Action integration", "Fine-grained PAT verification", "Organization-level SSO"],
        env_vars: ["GITHUB_CLIENT_ID", "GITHUB_CLIENT_SECRET"],
        description: "Essential for developer-focused applications and technical communities."
    },
    {
        id: "discord",
        name: "Discord",
        logo: ProviderLogos.discord,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code", "Implicit"],
        platforms: ["Web", "Desktop", "Mobile"],
        capabilities: ["Guild Join", "Role Verification", "Bot Integration"],
        limitations: "Strict rate limits on /users/@me endpoint.",
        future: ["Real-time presence sync", "Direct Message triggers", "App-level Commands auth"],
        env_vars: ["DISCORD_CLIENT_ID", "DISCORD_CLIENT_SECRET"],
        description: "Best for gaming, hobbyist communities, and crypto/Web3 projects."
    },
    {
        id: "facebook",
        name: "Facebook",
        logo: ProviderLogos.facebook,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code"],
        platforms: ["Web", "iOS", "Android"],
        capabilities: ["Profile Access", "Friend Lists (Restricted)", "Pages Manager"],
        limitations: "Strict App Review required for most permissions.",
        future: ["Instagram Cross-auth", "Facebook Workgroups mapping", "Meta Quest integration"],
        env_vars: ["FACEBOOK_APP_ID", "FACEBOOK_APP_SECRET"],
        description: "Broad reach for social applications and consumer-facing tools."
    },
    {
        id: "twitter",
        name: "Twitter (X)",
        logo: ProviderLogos.twitter,
        status: "available",
        type: "OAuth 2.0 / 1.0a",
        flows: ["PKCE", "Auth Code"],
        platforms: ["Web", "Mobile"],
        capabilities: ["Tweet Read/Write", "User Timeline", "Follower Checks"],
        limitations: "Expensive API tiers for high-volume data access.",
        future: ["Direct login from X-Blue", "Subscription verification", "Enhanced bot detection"],
        env_vars: ["TWITTER_CLIENT_ID", "TWITTER_CLIENT_SECRET"],
        description: "High-virality identity provider for real-time social platforms."
    },
    {
        id: "apple",
        name: "Apple",
        logo: ProviderLogos.apple,
        status: "beta",
        type: "OAuth 2.0 / OIDC",
        flows: ["Auth Code"],
        platforms: ["Web", "iOS", "macOS"],
        capabilities: ["Private Email Relay", "FaceID / TouchID support"],
        limitations: "Requires Apple Developer Program membership ($99/yr).",
        future: ["Native Passkey integration", "Subscription sync", "iCloud Data Vault access"],
        env_vars: ["APPLE_ID", "APPLE_TEAM_ID", "APPLE_KEY_ID", "APPLE_PRIVATE_KEY"],
        description: "High-privacy identity used primarily by mobile-first applications."
    },

    // --- ENTERPRISE & PRODUCTIVITY ---
    {
        id: "microsoft",
        name: "Microsoft",
        logo: ProviderLogos.microsoft,
        status: "available",
        type: "OIDC / OAuth 2.0 (Azure AD)",
        flows: ["PKCE", "Hybrid", "Client Credentials"],
        platforms: ["Web", "Windows", "Server"],
        capabilities: ["Multi-tenant support", "Graph API access"],
        limitations: "Requires verified publisher for custom scopes.",
        future: ["Auto-provisioning", "Directory Sync", "Condition Access Policies"],
        env_vars: ["MICROSOFT_CLIENT_ID", "MICROSOFT_CLIENT_SECRET", "MICROSOFT_TENANT_ID"],
        description: "Enterprise-grade identity for Office 365 and Azure ecosystems."
    },
    {
        id: "okta",
        name: "Okta",
        logo: ProviderLogos.okta,
        status: "coming_soon",
        type: "SAML / OIDC",
        flows: ["Auth Code", "Device Flow"],
        platforms: ["Enterprise Web", "Server"],
        capabilities: ["SSO Enforcement", "Directory Sync", "Custom Policies"],
        limitations: "Enterprise subscription required on the client side.",
        future: ["SCIM Provisioning", "Advanced Threat Protection", "Adaptive MFA"],
        env_vars: ["OKTA_DOMAIN", "OKTA_CLIENT_ID", "OKTA_CLIENT_SECRET"],
        description: "The global leader in enterprise workforce identity management."
    },
    {
        id: "slack",
        name: "Slack",
        logo: ProviderLogos.slack,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code"],
        platforms: ["Web", "Desktop"],
        capabilities: ["Workspace Auth", "Channel Management"],
        limitations: "User-token vs Bot-token complexity.",
        future: ["Shared channel permissions", "Granular scopes v3", "Enterprise Grid support"],
        env_vars: ["SLACK_CLIENT_ID", "SLACK_CLIENT_SECRET"],
        description: "Perfect for productivity tools and internal business apps."
    },
    {
        id: "linkedin",
        name: "LinkedIn",
        logo: ProviderLogos.linkedin,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code"],
        platforms: ["Web"],
        capabilities: ["Professional Profile", "Connection Counts"],
        limitations: "V2 API scopes are highly restricted.",
        future: ["B2B lead generation hooks", "Verified worker status", "Company Page auth"],
        env_vars: ["LINKEDIN_CLIENT_ID", "LINKEDIN_CLIENT_SECRET"],
        description: "The primary provider for professional networking and B2B SaaS."
    },
    {
        id: "salesforce",
        name: "Salesforce",
        logo: ProviderLogos.salesforce,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Web Server", "User Agent"],
        platforms: ["Web", "Mobile"],
        capabilities: ["CRM Data Access", "Apex Triggers"],
        limitations: "Complex scope management for professional editions.",
        future: ["Tableau integration", "MuleSoft event streaming", "Slack-CRMSync"],
        env_vars: ["SALESFORCE_CLIENT_ID", "SALESFORCE_CLIENT_SECRET"],
        description: "Enterprise identity for the world's #1 CRM platform."
    },
    {
        id: "notion",
        name: "Notion",
        logo: ProviderLogos.notion,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code"],
        platforms: ["Web", "Desktop"],
        capabilities: ["Page Content Read", "Database Management"],
        limitations: "Cannot access private pages without explicit invite.",
        future: ["Template-based provisioning", "Inline block comments API"],
        env_vars: ["NOTION_CLIENT_ID", "NOTION_CLIENT_SECRET"],
        description: "Connect and sync data with the modern workspace."
    },
    {
        id: "zoom",
        name: "Zoom",
        logo: ProviderLogos.zoom,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code", "PKCE"],
        platforms: ["Web", "Desktop", "Mobile"],
        capabilities: ["Meeting Scheduling", "Recording Management"],
        limitations: "Requires marketplace approval for public apps.",
        future: ["Real-time transcript stream", "Whiteboard API", "Native Apps SDK"],
        env_vars: ["ZOOM_CLIENT_ID", "ZOOM_CLIENT_SECRET"],
        description: "Powering modern video communication and collaboration."
    },
    {
        id: "asana",
        name: "Asana",
        logo: ProviderLogos.asana,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code", "Implicit"],
        platforms: ["Web", "Mobile"],
        capabilities: ["Task Sync", "Project Management"],
        limitations: "Personal access tokens have separate rate limits.",
        future: ["Timeline API", "Custom Fields streaming", "Workload auto-sync"],
        env_vars: ["ASANA_CLIENT_ID", "ASANA_CLIENT_SECRET"],
        description: "Work management and productivity for high-performance teams."
    },

    // --- DEV TOOLS & INFRA ---
    {
        id: "gitlab",
        name: "GitLab",
        logo: ProviderLogos.gitlab,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code", "PKCE"],
        platforms: ["Web", "Self-hosted"],
        capabilities: ["CI/CD Pipeline Access", "Registry Management"],
        limitations: "Custom scopes require admin approval on some instances.",
        future: ["Geo-replication auth", "Runner auto-provisioning", "Security Dashboard API"],
        env_vars: ["GITLAB_CLIENT_ID", "GITLAB_CLIENT_SECRET"],
        description: "DevOps platform for the entire software lifecycle."
    },
    {
        id: "bitbucket",
        name: "Bitbucket",
        logo: ProviderLogos.bitbucket,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code", "Implicit"],
        platforms: ["Web", "Cloud"],
        capabilities: ["Repository Read/Write", "Deployment Hooks"],
        limitations: "Strict branch permission enforcement.",
        future: ["Pipeline deep-integration", "Jira Cloud auto-sync"],
        env_vars: ["BITBUCKET_CLIENT_ID", "BITBUCKET_CLIENT_SECRET"],
        description: "Git solution optimized for teams using Jira and Trello."
    },
    {
        id: "digitalocean",
        name: "DigitalOcean",
        logo: ProviderLogos.digitalocean,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code"],
        platforms: ["Web", "CLI"],
        capabilities: ["Droplet Control", "Kubernetes Management"],
        limitations: "Account-level API tokens only.",
        future: ["App Platform streaming", "Database cluster auth"],
        env_vars: ["DIGITALOCEAN_CLIENT_ID", "DIGITALOCEAN_CLIENT_SECRET"],
        description: "Simple cloud infrastructure for developers."
    },
    {
        id: "heroku",
        name: "Heroku",
        logo: ProviderLogos.heroku,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code"],
        platforms: ["Web", "CLI"],
        capabilities: ["Dyno Management", "Log Drains"],
        limitations: "SSO only available for Enterprise Teams.",
        future: ["Add-on marketplace SSO", "Private Space auto-provision"],
        env_vars: ["HEROKU_CLIENT_ID", "HEROKU_CLIENT_SECRET"],
        description: "PaaS platform for building and running modern apps."
    },
    {
        id: "netlify",
        name: "Netlify",
        logo: ProviderLogos.netlify,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code"],
        platforms: ["Web"],
        capabilities: ["Site Deployments", "Form Handling", "Edge Functions"],
        limitations: "Personal accounts restricted to 100 API calls/min.",
        future: ["Identity-level hooks", "Edge State sync"],
        env_vars: ["NETLIFY_CLIENT_ID", "NETLIFY_CLIENT_SECRET"],
        description: "Build, deploy, and scale modern web projects."
    },

    // --- E-COMMERCE & PAYMENTS ---
    {
        id: "paypal",
        name: "PayPal",
        logo: ProviderLogos.paypal,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code"],
        platforms: ["Web", "Mobile"],
        capabilities: ["Payment Verification", "Verify Addresses"],
        limitations: "Sandbox vs Live environment separation.",
        future: ["Subscription auto-renew auth", "Dispute management API"],
        env_vars: ["PAYPAL_CLIENT_ID", "PAYPAL_CLIENT_SECRET"],
        description: "Trustworthy identity for commerce and financial apps."
    },
    {
        id: "stripe",
        name: "Stripe",
        logo: ProviderLogos.stripe,
        status: "available",
        type: "OAuth 2.0 (Connect)",
        flows: ["Auth Code"],
        platforms: ["Web", "Mobile", "POS"],
        capabilities: ["Platform Connect", "Payout Controls"],
        limitations: "Requires Stripe Connect for cross-account auth.",
        future: ["Terminal local auth", "Tax ID verification stream"],
        env_vars: ["STRIPE_CLIENT_ID", "STRIPE_SECRET_KEY"],
        description: "Financial infrastructure for the internet."
    },
    {
        id: "shopify",
        name: "Shopify",
        logo: ProviderLogos.shopify,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code"],
        platforms: ["Web", "Mobile"],
        capabilities: ["Order Access", "Inventory Management"],
        limitations: "Store-specific URL required for initial handshake.",
        future: ["Hydrogen-ready auth", "Point of Sale sync"],
        env_vars: ["SHOPIFY_API_KEY", "SHOPIFY_API_SECRET"],
        description: "Powering independent businesses everywhere."
    },

    // --- SOCIAL & MEDIA ---
    {
        id: "instagram",
        name: "Instagram",
        logo: ProviderLogos.instagram,
        status: "available",
        type: "OAuth 2.0 (Basic Display)",
        flows: ["Auth Code"],
        platforms: ["Web", "iOS", "Android"],
        capabilities: ["Media Metadata", "Profile Info"],
        limitations: "Long-lived tokens expire every 60 days.",
        future: ["Reels publishing API", "Direct Message integration"],
        env_vars: ["INSTAGRAM_APP_ID", "INSTAGRAM_APP_SECRET"],
        description: "Visual identity for creators and brands."
    },
    {
        id: "tiktok",
        name: "TikTok",
        logo: ProviderLogos.tiktok,
        status: "beta",
        type: "OAuth 2.0",
        flows: ["Auth Code"],
        platforms: ["Mobile"],
        capabilities: ["Video Stats", "Creator Info"],
        limitations: "Highly restricted research API.",
        future: ["Live commerce triggers", "Effect House sync"],
        env_vars: ["TIKTOK_CLIENT_KEY", "TIKTOK_CLIENT_SECRET"],
        description: "Identity for the world's most engaging short-form video platform."
    },
    {
        id: "pinterest",
        name: "Pinterest",
        logo: ProviderLogos.pinterest,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code"],
        platforms: ["Web", "Mobile"],
        capabilities: ["Board Management", "Pin Creation"],
        limitations: "Rate limited to 1000 pins per day per user.",
        future: ["AR Try-on sync", "Commerce tagging API"],
        env_vars: ["PINTEREST_APP_ID", "PINTEREST_APP_SECRET"],
        description: "Discover and save creative ideas."
    },
    {
        id: "spotify",
        name: "Spotify",
        logo: ProviderLogos.spotify,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code", "Implicit"],
        platforms: ["Web", "Desktop", "Spotify App"],
        capabilities: ["Playlist Control", "Playback Sync", "User Libraries"],
        limitations: "High-volume requests require manual app approval.",
        future: ["Ad-tier verification", "Group session auth", "Podcast management hooks"],
        env_vars: ["SPOTIFY_CLIENT_ID", "SPOTIFY_CLIENT_SECRET"],
        description: "Integration-heavy provider for audio and music-focused applications."
    },
    {
        id: "twitch",
        name: "Twitch",
        logo: ProviderLogos.twitch,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code", "Implicit"],
        platforms: ["Web", "Desktop", "Console"],
        capabilities: ["Stream Key Access", "Chat Control", "Subscription Status"],
        limitations: "PubSub limits for real-time events.",
        future: ["Drops management", "Extension-level SSO"],
        env_vars: ["TWITCH_CLIENT_ID", "TWITCH_CLIENT_SECRET"],
        description: "The primary provider for the live streaming ecosystem."
    },

    // --- REGIONAL GIANTS ---
    {
        id: "line",
        name: "LINE",
        logo: ProviderLogos.line,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code"],
        platforms: ["Web", "Mobile (Japan)"],
        capabilities: ["Profile Sync", "Messaging API"],
        limitations: "Strict data sovereignty rules for EU users.",
        future: ["Liff-app deep integration", "Payment-state auth"],
        env_vars: ["LINE_CHANNEL_ID", "LINE_CHANNEL_SECRET"],
        description: "Dominant communication provider in Japan and South East Asia."
    },
    {
        id: "kakao",
        name: "Kakao",
        logo: ProviderLogos.kakao,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code"],
        platforms: ["Mobile (Korea)"],
        capabilities: ["Talk Profile", "Friend List Sync"],
        limitations: "Documentation primarily in Korean.",
        future: ["Kakao Pay verification", "Native app auto-auth"],
        env_vars: ["KAKAO_NATIVE_KEY", "KAKAO_REST_KEY"],
        description: "Essential for entering the South Korean market."
    },
    {
        id: "naver",
        name: "Naver",
        logo: ProviderLogos.naver,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code"],
        platforms: ["Web (Korea)"],
        capabilities: ["Verified Identity", "Blog/Cafe Access"],
        limitations: "Complex verification for international developers.",
        future: ["Search console integration", "Whale browser SSO"],
        env_vars: ["NAVER_CLIENT_ID", "NAVER_CLIENT_SECRET"],
        description: "The 'Google of Korea' providing verified user data."
    },
    {
        id: "yandex",
        name: "Yandex",
        logo: ProviderLogos.yandex,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code"],
        platforms: ["Web (Russia)"],
        capabilities: ["Drive Access", "Mail Metadata"],
        limitations: "Data residency compliance required.",
        future: ["Smart TV auth", "Taxi/Delivery ID sync"],
        env_vars: ["YANDEX_CLIENT_ID", "YANDEX_CLIENT_SECRET"],
        description: "Leading technology and identity provider in Eurasia."
    },
    {
        id: "vk",
        name: "VK",
        logo: ProviderLogos.vk,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code"],
        platforms: ["Web", "Mobile (Russia)"],
        capabilities: ["Wall Posting", "Direct Messages"],
        limitations: "Strict app moderation for private data access.",
        future: ["Mini-apps bridge", "Audio track verification"],
        env_vars: ["VK_APP_ID", "VK_SECRET_KEY"],
        description: "The largest social network in Eastern Europe."
    },

    // --- MISC & UTILITY ---
    {
        id: "dropbox",
        name: "Dropbox",
        logo: ProviderLogos.dropbox,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code", "PKCE"],
        platforms: ["Web", "Desktop"],
        capabilities: ["File Metadata", "Shared Links Creation"],
        limitations: "App folder vs Full folder permissions.",
        future: ["Paper API sync", "Team Space management"],
        env_vars: ["DROPBOX_APP_KEY", "DROPBOX_APP_SECRET"],
        description: "Secure file storage and collaboration identity."
    },
    {
        id: "box",
        name: "Box",
        logo: ProviderLogos.box,
        status: "available",
        type: "OAuth 2.0 / JWT",
        flows: ["Auth Code", "App Auth"],
        platforms: ["Enterprise Web"],
        capabilities: ["E-signature Integration", "Governance Policies"],
        limitations: "Complex App-user model.",
        future: ["Shield security events", "Relay workflow triggers"],
        env_vars: ["BOX_CLIENT_ID", "BOX_CLIENT_SECRET"],
        description: "Content management and security for business-critical data."
    },
    {
        id: "wordpress",
        name: "WordPress",
        logo: ProviderLogos.wordpress,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code"],
        platforms: ["Web"],
        capabilities: ["Post Creation", "Media Library Access"],
        limitations: "Requires Jetpack for .com SSO.",
        future: ["Gutenberg block sync", "Plugin-level auth"],
        env_vars: ["WORDPRESS_CLIENT_ID", "WORDPRESS_CLIENT_SECRET"],
        description: "Connect to the engine powering 40% of the web."
    },
    {
        id: "strava",
        name: "Strava",
        logo: ProviderLogos.strava,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code"],
        platforms: ["Mobile", "Wearables"],
        capabilities: ["Activity Tracking", "Route Sync"],
        limitations: "Requires high-res logo usage for app compliance.",
        future: ["Club-level analytics", "Segment leaderboard API"],
        env_vars: ["STRAVA_CLIENT_ID", "STRAVA_CLIENT_SECRET"],
        description: "The #1 provider for fitness and athletic identity."
    },
    {
        id: "fitbit",
        name: "Fitbit",
        logo: ProviderLogos.fitbit,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code", "PKCE"],
        platforms: ["Mobile", "Wearables"],
        capabilities: ["Sleep Data", "Heart Rate Stream"],
        limitations: "Requires explicit user consent for health data.",
        future: ["Google Fit cross-sync", "Premium feature verification"],
        env_vars: ["FITBIT_CLIENT_ID", "FITBIT_CLIENT_SECRET"],
        description: "Identity for digital health and wellness tracker ecosystems."
    },
    {
        id: "evernote",
        name: "Evernote",
        logo: ProviderLogos.evernote,
        status: "available",
        type: "OAuth 1.0a (Legacy)",
        flows: ["Auth Code"],
        platforms: ["Web", "Desktop"],
        capabilities: ["Note Creation", "Notebook Search"],
        limitations: "Strict sandbox testing required for production keys.",
        future: ["V2 REST API", "AI Note extraction auth"],
        env_vars: ["EVERNOTE_CONSUMER_KEY", "EVERNOTE_CONSUMER_SECRET"],
        description: "Remember everything with the world's most popular note-taker."
    },
    {
        id: "hubspot",
        name: "HubSpot",
        logo: ProviderLogos.hubspot,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code"],
        platforms: ["Web"],
        capabilities: ["Contact Management", "Deal Tracking"],
        limitations: "Strict 10-site limit for public apps.",
        future: ["Custom object streaming", "Marketing hub auth"],
        env_vars: ["HUBSPOT_CLIENT_ID", "HUBSPOT_CLIENT_SECRET"],
        description: "CRM and marketing automation identity for growth teams."
    },
    {
        id: "reddit",
        name: "Reddit",
        logo: ProviderLogos.reddit,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code", "Implicit"],
        platforms: ["Web", "Mobile"],
        capabilities: ["Subreddit Mapping", "Karma Verification", "Mod Tools"],
        limitations: "Strict subreddit-specific access controls.",
        future: ["Community Points sync", "Native vault integration", "Direct mod-mail auth"],
        env_vars: ["REDDIT_CLIENT_ID", "REDDIT_CLIENT_SECRET"],
        description: "Connect with internet communities through verified Reddit accounts."
    },
    {
        id: "magic-link",
        name: "Magic Link",
        logo: ProviderLogos["magic-link"],
        status: "available",
        type: "Passwordless / SMTP",
        flows: ["One-time Token"],
        platforms: ["Web", "Mobile"],
        capabilities: ["No-password required", "Instant verification"],
        limitations: "Requires high-reputation SMTP or SendGrid/Postmark.",
        future: ["Cross-device link tracking", "Custom fallback methods", "Webhook-based auth events"],
        env_vars: ["SMTP_HOST", "SMTP_USER", "SMTP_PASSWORD"],
        description: "Frictionless authentication using single-use email links."
    },
    {
        id: "stackexchange",
        name: "Stack Exchange",
        logo: ProviderLogos.stackexchange,
        status: "available",
        type: "OAuth 2.0",
        flows: ["Auth Code", "Implicit"],
        platforms: ["Web"],
        capabilities: ["Profile Reputation", "Answer Sync"],
        limitations: "Filter-based API results can be complex.",
        future: ["Stack Overflow for Teams SSO", "Collective-level auth"],
        env_vars: ["STACKEXCHANGE_CLIENT_ID", "STACKEXCHANGE_CLIENT_SECRET", "STACKEXCHANGE_KEY"],
        description: "The primary provider for the global developer knowledge network."
    },
    {
        id: "medium",
        name: "Medium",
        logo: ProviderLogos.medium,
        status: "available",
        type: "OAuth 2.0 / Integration Token",
        flows: ["Auth Code"],
        platforms: ["Web"],
        capabilities: ["Publication Access", "Post Drafting"],
        limitations: "Rate limit of 100 posts per day.",
        future: ["Partner Program payout status", "Clap-analytics API"],
        env_vars: ["MEDIUM_CLIENT_ID", "MEDIUM_CLIENT_SECRET"],
        description: "Connect with the largest network of writers and storytellers."
    },
    {
        id: "atlassian",
        name: "Atlassian",
        logo: ProviderLogos.atlassian,
        status: "available",
        type: "OAuth 2.0 (3LO)",
        flows: ["Auth Code"],
        platforms: ["Web", "Jira Cloud", "Confluence"],
        capabilities: ["Issue Management", "Space Configuration"],
        limitations: "Requires 'CloudID' mapping for each tenant.",
        future: ["Forge-app bridge", "Opsgenie alert sync"],
        env_vars: ["ATLASSIAN_CLIENT_ID", "ATLASSIAN_CLIENT_SECRET"],
        description: "Identity for Jira, Confluence, and the Atlassian ecosystem."
    },
    {
        id: "auth0",
        name: "Auth0",
        logo: ProviderLogos.auth0,
        status: "beta",
        type: "OIDC / OAuth 2.0",
        flows: ["Auth Code", "PKCE", "Universal Login"],
        platforms: ["Web", "Mobile", "Enterprise"],
        capabilities: ["Universal Login", "Multi-factor Enrollment"],
        limitations: "Requires existing Auth0 tenant.",
        future: ["Organization-specific flows", "Action-hooks triggers"],
        env_vars: ["AUTH0_DOMAIN", "AUTH0_CLIENT_ID", "AUTH0_CLIENT_SECRET"],
        description: "Federated identity for enterprise and b2c apps."
    },
    {
        id: "firebase",
        name: "Firebase",
        logo: ProviderLogos.firebase,
        status: "coming_soon",
        type: "Identity Platform",
        flows: ["Custom Token", "Phone Auth"],
        platforms: ["Mobile", "Web"],
        capabilities: ["Real-time DB Auth", "Multi-platform Sync"],
        limitations: "Google Cloud Project mapping required.",
        future: ["Firestore Rules sync", "Cloud Functions auth"],
        env_vars: ["FIREBASE_API_KEY", "FIREBASE_PROJECT_ID"],
        description: "Identity and session bridge for Firebase-driven applications."
    },
    {
        id: "ping-identity",
        name: "Ping Identity",
        logo: ProviderLogos["ping-identity"],
        status: "coming_soon",
        type: "SAML / OIDC",
        flows: ["Auth Code", "Hybrid"],
        platforms: ["Enterprise Web"],
        capabilities: ["Workforce Identity", "Risk-based Auth"],
        limitations: "Highly complex OIDC profile setup.",
        future: ["DaVinci orchestrator sync", "Fraud detection metrics"],
        env_vars: ["PING_BASE_URL", "PING_CLIENT_ID", "PING_CLIENT_SECRET"],
        description: "Specialized enterprise identity for Fortune 500 companies."
    },
    {
        id: "onelogin",
        name: "OneLogin",
        logo: ProviderLogos.onelogin,
        status: "coming_soon",
        type: "SAML / OIDC",
        flows: ["Auth Code"],
        platforms: ["Enterprise Web"],
        capabilities: ["Directory Sync", "Provisioning"],
        limitations: "Requires OneLogin API credentials + Client IDs.",
        future: ["SmartFactor MFA sync", "Desktop-to-Cloud SSO"],
        env_vars: ["ONELOGIN_SUBDOMAIN", "ONELOGIN_CLIENT_ID", "ONELOGIN_CLIENT_SECRET"],
        description: "Cloud-based identity and access management for teams."
    },
];
